### ISSUE TITLE
[bug] can not use 「Packal Workflows 」

### ISSUE THREAD

**Issue by ljh2023** [deanishe/alfred-packal-search#1]
I download this workflow from packal and I call alfred to type this command. However, I can not see any results.

For example, I type 「Packal Workflows timer」, the result is nothing. But when I type 「Packal Tags 」It just works very well.
# 

My system: OSX 10.10.2

Alfred version: V2 , and license is mega
# 

Although encounter this problem, I love this workflow, thank you!

**Comment by ljh2023** [comment]
Ok, it's my mistake, i take the "loading" as no responding. But it's too long to get the result! I search timer and wait nearly 5 minutes and get nothing.

**Comment by deanishe** [comment]
That should only happen the very first time you use it. The problem is that because it updates its list of workflows in the background, the first time you run it, there are no workflows to show.

It's still a bug, though. The workflow was supposed to inform you when that happens. I've fixed it in [v1.2](https://github.com/deanishe/alfred-packal-search/releases/tag/v1.2)
